name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    # Cache the build artifacts and dependencies
    - name: Cache Swift dependencies
      uses: actions/cache@v4.2.0
      with:
        path: |
          ~/.swiftpm
          .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 17.2
        postgresql db: testing
        postgresql user: testing
        postgresql password: testing

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
